version: "3.8"

services:
  nimbus-db:
    image: postgres:18-alpine
    container_name: nimbus-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - nimbus-pgdata:/var/lib/postgresql/data

volumes:
  nimbus-pgdata:
